# List of companies we are tracking for insider trading analysis

COMPANIES = [
    {"name": "Apple",                 "ticker": "AAPL",  "sector": "Technology",      "cap": "large"},
    {"name": "Microsoft",             "ticker": "MSFT",  "sector": "Technology",      "cap": "large"},
    {"name": "JPMorgan Chase",        "ticker": "JPM",   "sector": "Finance",         "cap": "large"},
    {"name": "Tesla",                 "ticker": "TSLA",  "sector": "Auto/EV",         "cap": "large"},
    {"name": "Amazon",                "ticker": "AMZN",  "sector": "Consumer",        "cap": "large"},
    {"name": "Goldman Sachs",         "ticker": "GS",    "sector": "Finance",         "cap": "large"},
    {"name": "ExxonMobil",            "ticker": "XOM",   "sector": "Energy",          "cap": "large"},
    {"name": "Johnson & Johnson",     "ticker": "JNJ",   "sector": "Healthcare",      "cap": "large"},
    {"name": "Nvidia",                "ticker": "NVDA",  "sector": "Technology",      "cap": "large"},
    {"name": "Netflix",               "ticker": "NFLX",  "sector": "Entertainment",   "cap": "large"},
    {"name": "Cloudflare",            "ticker": "NET",   "sector": "Technology",      "cap": "mid"},
    {"name": "Occidental Petroleum",  "ticker": "OXY",   "sector": "Energy",          "cap": "mid"},
    {"name": "Nike",                  "ticker": "NKE",   "sector": "Consumer/Sports", "cap": "large"},
    {"name": "Moderna",               "ticker": "MRNA",  "sector": "Healthcare",      "cap": "mid"},
    {"name": "Coinbase",              "ticker": "COIN",  "sector": "Finance/Crypto",  "cap": "mid"},
    {"name": "Dell Technologies",     "ticker": "DELL",  "sector": "Technology",      "cap": "large"},
    {"name": "DraftKings",            "ticker": "DKNG",  "sector": "Gaming",          "cap": "mid"},
    {"name": "Marriott International","ticker": "MAR",   "sector": "Hospitality",     "cap": "large"},
    {"name": "Uber",                  "ticker": "UBER",  "sector": "Transport",       "cap": "large"},
    {"name": "Meta",                  "ticker": "META",  "sector": "Technology",      "cap": "large"},
    {"name": "Alphabet",              "ticker": "GOOGL", "sector": "Technology",      "cap": "large"},
    {"name": "Visa",                  "ticker": "V",     "sector": "Finance",         "cap": "large"},
    {"name": "Mastercard",            "ticker": "MA",    "sector": "Finance",         "cap": "large"},
    {"name": "Pfizer",                "ticker": "PFE",   "sector": "Healthcare",      "cap": "large"},
    {"name": "Bank of America",       "ticker": "BAC",   "sector": "Finance",         "cap": "large"},
    {"name": "Walmart",               "ticker": "WMT",   "sector": "Retail",          "cap": "large"},
    {"name": "Disney",                "ticker": "DIS",   "sector": "Entertainment",   "cap": "large"},
    {"name": "AMD",                   "ticker": "AMD",   "sector": "Technology",      "cap": "large"},
    {"name": "Adobe",                 "ticker": "ADBE",  "sector": "Technology",      "cap": "large"},
    {"name": "Roblox",                "ticker": "RBLX",  "sector": "Gaming",          "cap": "mid"},
    {"name": "Snap",                  "ticker": "SNAP",  "sector": "Technology",      "cap": "mid"},
    {"name": "Lyft",                  "ticker": "LYFT",  "sector": "Transport",       "cap": "mid"},
    {"name": "Robinhood",             "ticker": "HOOD",  "sector": "Finance/Crypto",  "cap": "mid"},
    {"name": "Rivian",                "ticker": "RIVN",  "sector": "Auto/EV",         "cap": "mid"},
    {"name": "SoFi",                  "ticker": "SOFI",  "sector": "Finance",         "cap": "mid"},
    {"name": "DoorDash",              "ticker": "DASH",  "sector": "Transport",       "cap": "mid"},
    {"name": "Airbnb",                "ticker": "ABNB",  "sector": "Hospitality",     "cap": "mid"},
    {"name": "Pinterest",             "ticker": "PINS",  "sector": "Technology",      "cap": "mid"},
    {"name": "CrowdStrike",           "ticker": "CRWD",  "sector": "Technology",      "cap": "mid"},
    {"name": "Salesforce",            "ticker": "CRM",   "sector": "Technology",      "cap": "large"},
]